LOAD DATA
INFILE 'Products_cleaned.csv'
APPEND
INTO TABLE PRODUCTS
FIELDS CSV WITH EMBEDDED
TRAILING NULLCOLS
(
    PRODUCT_ID   INTEGER EXTERNAL,
    SKU          CHAR,
    CATEGORY     CHAR,
    UNIT_PRICE   DECIMAL EXTERNAL,
    BRAND        CHAR
)
