LOAD DATA
INFILE 'Customers_cleaned.csv'
APPEND
INTO TABLE CUSTOMERS
FIELDS CSV WITH EMBEDDED
TRAILING NULLCOLS
(
    CUSTOMER_ID       INTEGER EXTERNAL,
    CUSTOMER_NAME     CHAR,
    CITY              CHAR,
    CUSTOMER_SEGMENT  CHAR
)
