LOAD DATA
INFILE 'Orders_cleaned.csv'
APPEND
INTO TABLE ORDERS
FIELDS CSV WITH EMBEDDED
TRAILING NULLCOLS
(
    ORDER_ID               INTEGER EXTERNAL,
    ORDER_DATE             DATE "YYYY-MM-DD",
    CUSTOMER_ID            INTEGER EXTERNAL,
    PRODUCT_ID             INTEGER EXTERNAL,
    QUANTITY               INTEGER EXTERNAL,
    ORDER_VALUE            DECIMAL EXTERNAL,
    ORDER_STATUS           CHAR,
    PAYMENT_METHOD         CHAR,
    RATING                 INTEGER EXTERNAL,
    ORDER_YEAR             INTEGER EXTERNAL,
    ORDER_MONTH            INTEGER EXTERNAL,
    ORDER_YEAR_MONTH       CHAR,
    COMPUTED_VALUE         DECIMAL EXTERNAL,
    VALUE_VARIANCE         DECIMAL EXTERNAL,
    VALUE_VARIANCE_PCT     DECIMAL EXTERNAL,
    IS_DELIVERED_RATING    CHAR,
    IS_ORDERVALUE_OUTLIER  CHAR,
    IS_PARTIAL_PERIOD      CHAR
)
